exports.JsWarrior = 
  version: '0.0.1'
  Floor: require('./js_warrior/floor').Floor
  Game: require('./js_warrior/game').Game
  Level: require('./js_warrior/level').Level
  LevelLoader: require('./js_warrior/level_loader').LevelLoader
  Position: require('./js_warrior/position').Position
  Profile: require('./js_warrior/profile').Profile
  Space: require('./js_warrior/space').Space
  Tower: require('./js_warrior/tower').Tower
  Abilities: require('./js_warrior/abilities').Abilities
  Units: require('./js_warrior/units').Units
  Utils: require('./js_warrior/utils').Utils
  Turn:  require('./js_warrior/turn').Turn
  Views: require('./js_warrior/views').Views