exports.JsWarrior = 
  version: '0.0.1'
  Floor: require('./js_warrior/floor').Floor
  Game: require('./js_warrior/game').Game
  Level: require('./js_warrior/level').Level
  Position: require('./js_warrior/position').Position
  Space: require('./js_warrior/space').Space
  Abilities: require('./js_warrior/abilities').Abilities
  Units: require('./js_warrior/units').Units