exports.Abilities = 
  BaseAbilities: require('./abilities/base_abilities').BaseAbilities
  Sense: require('./abilities/sense').Sense
  Action: require('./abilities/action').Action  
  Attack: require('./abilities/attack').Attack
  Feel: require('./abilities/feel').Feel
  Explode: require('./abilities/explode').Explode
  Walk: require('./abilities/walk').Walk
  Health: require('./abilities/health').Health
  Rest: require('./abilities/rest').Rest